// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx89cLrhRFCdQQNCvSoeSdr47e17G8U34',
    appId: '1:522675172773:web:your-web-app-id',
    messagingSenderId: '522675172773',
    projectId: 'chatup-1ec88',
    authDomain: 'chatup-1ec88.firebaseapp.com',
    storageBucket: 'chatup-1ec88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx89cLrhRFCdQQNCvSoeSdr47e17G8U34',
    appId: '1:522675172773:android:a078bcb161cdcea3dda44c',
    messagingSenderId: '522675172773',
    projectId: 'chatup-1ec88',
    storageBucket: 'chatup-1ec88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx89cLrhRFCdQQNCvSoeSdr47e17G8U34',
    appId: '1:522675172773:ios:your-ios-app-id',
    messagingSenderId: '522675172773',
    projectId: 'chatup-1ec88',
    storageBucket: 'chatup-1ec88.appspot.com',
    iosBundleId: 'com.example.chatup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx89cLrhRFCdQQNCvSoeSdr47e17G8U34',
    appId: '1:522675172773:macos:your-macos-app-id',
    messagingSenderId: '522675172773',
    projectId: 'chatup-1ec88',
    storageBucket: 'chatup-1ec88.appspot.com',
    iosBundleId: 'com.example.chatup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx89cLrhRFCdQQNCvSoeSdr47e17G8U34',
    appId: '1:522675172773:windows:your-windows-app-id',
    messagingSenderId: '522675172773',
    projectId: 'chatup-1ec88',
    authDomain: 'chatup-1ec88.firebaseapp.com',
    storageBucket: 'chatup-1ec88.appspot.com',
  );
}
